changes to force output to specific channels
somakeit/slack-smib pull request #5
Opened 2019-04-04 01:26 UTC by abrugsch

To prevent DM'ing the bot to do things surreptitiously, privacy sensitive scripts  like webcam and enhance should only place results in the specified FORCE_CHANNEL location

2019-04-04 08:16 UTC, brackendawson requested changes

2019-04-04 08:16 UTC, brackendawson commented on smib.py
> +                                if len(lines) >= 1:
Here onward should be outside of the try block.

2019-04-04 08:16 UTC, brackendawson commented on smib.py
> +                                        postchannel = postchannel[14:].lower()
Probably put "FORCE CHANNEL:" in a constant and len it here rather than 14.

2019-04-04 11:09 UTC, abrugsch commented
additional commit added to PR

2019-05-16 21:33 UTC, brackendawson approved these changes

2019-05-16 21:33 UTC, merged